# Generated by Django 5.2.7 on 2025-11-24 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('competencias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente de Validación'), ('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('INACTIVO', 'Inactivo/Baja')], default='PENDIENTE', max_length=20)),
                ('codigo_unico', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('es_invitado', models.BooleanField(default=False)),
                ('departamento_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo_suspension', models.TextField(blank=True, help_text='Razón de la sanción si está suspendido', null=True)),
                ('fecha_suspension', models.DateField(blank=True, null=True)),
                ('suspension_indefinida', models.BooleanField(default=False)),
                ('fin_suspension', models.DateField(blank=True, help_text='Dejar vacío si es indefinida', null=True)),
                ('es_historico', models.BooleanField(default=False, help_text='Deportista de gestiones pasadas importado')),
                ('force_password_change', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archivo_responsabilidad', models.FileField(blank=True, null=True, upload_to='responsabilidades/')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deportistas', to='clubs.club')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deportista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Corta', 'Arma Corta'), ('Larga', 'Arma Larga'), ('Escopeta', 'Escopeta')], max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('calibre', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=100, unique=True)),
                ('matricula', models.CharField(blank=True, max_length=100, null=True)),
                ('es_aire_comprimido', models.BooleanField(default=False)),
                ('fecha_inspeccion', models.DateField(blank=True, help_text='Válida por la gestión actual', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('deportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armas', to='deportistas.deportista')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoDeportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CI', 'Cédula de Identidad'), ('Licencia B', 'Licencia Cat. B'), ('Responsabilidad', 'Carta de Responsabilidad'), ('Otro', 'Otro Documento')], max_length=50)),
                ('file', models.FileField(upload_to='docs_deportistas/')),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='deportistas.deportista')),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoArma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('arma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportistas.arma')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.competencia')),
                ('deportista_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_otorgados', to='deportistas.deportista')),
                ('deportista_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_recibidos', to='deportistas.deportista')),
            ],
            options={
                'unique_together': {('arma', 'competencia', 'deportista_receptor')},
            },
        ),
    ]
