# Generated by Django 5.2.7 on 2025-10-04 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('birth_date', models.DateField()),
                ('departamento', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('foto_path', models.ImageField(blank=True, null=True, upload_to='fotos_deportistas/')),
                ('status', models.CharField(choices=[('Pendiente de Aprobación', 'Pendiente de Aprobación'), ('Activo', 'Activo'), ('Suspendido', 'Suspendido'), ('Rechazado', 'Rechazado')], default='Pendiente de Aprobación', max_length=50)),
                ('notas_admin', models.TextField(blank=True, null=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.club')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('calibre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_matricula', models.CharField(max_length=100)),
                ('fecha_inspeccion', models.DateField(blank=True, null=True)),
                ('file_path', models.FileField(upload_to='matriculas_armas/')),
                ('deportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armas', to='deportistas.deportista')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Licencia B', 'Licencia B (PDF)'), ('Carnet de Identidad', 'Carnet de Identidad (PDF)'), ('Licencia de Competencia', 'Licencia de Competencia')], max_length=50)),
                ('file_path', models.FileField(upload_to='documentos_deportistas/')),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('deportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='deportistas.deportista')),
            ],
        ),
    ]
