# Generated by Django 5.2.8 on 2025-11-25 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Corta', 'Arma Corta'), ('Larga', 'Arma Larga'), ('Escopeta', 'Escopeta')], max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('calibre', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=100, unique=True)),
                ('matricula', models.CharField(blank=True, max_length=100, null=True)),
                ('es_aire_comprimido', models.BooleanField(default=False)),
                ('fecha_inspeccion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoDeportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CI', 'Cédula'), ('Licencia B', 'Licencia'), ('Responsabilidad', 'Responsabilidad'), ('Otro', 'Otro')], max_length=50)),
                ('file', models.FileField(upload_to='docs_deportistas/')),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoArma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('INACTIVO', 'Inactivo')], default='PENDIENTE', max_length=20)),
                ('codigo_unico', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('es_invitado', models.BooleanField(default=False)),
                ('departamento_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo_suspension', models.TextField(blank=True, null=True)),
                ('fecha_suspension', models.DateField(blank=True, null=True)),
                ('suspension_indefinida', models.BooleanField(default=False)),
                ('fin_suspension', models.DateField(blank=True, null=True)),
                ('es_historico', models.BooleanField(default=False)),
                ('force_password_change', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archivo_responsabilidad', models.FileField(blank=True, null=True, upload_to='responsabilidades/')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deportistas', to='clubs.club')),
            ],
        ),
    ]
