# Generated by Django 5.2.8 on 2025-11-25 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competencias', '0002_initial'),
        ('deportistas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deportista',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deportista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arma',
            name='deportista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armas', to='deportistas.deportista'),
        ),
        migrations.AddField(
            model_name='documentodeportista',
            name='deportista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='deportistas.deportista'),
        ),
        migrations.AddField(
            model_name='prestamoarma',
            name='arma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportistas.arma'),
        ),
        migrations.AddField(
            model_name='prestamoarma',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.competencia'),
        ),
        migrations.AddField(
            model_name='prestamoarma',
            name='deportista_propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_otorgados', to='deportistas.deportista'),
        ),
        migrations.AddField(
            model_name='prestamoarma',
            name='deportista_receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_recibidos', to='deportistas.deportista'),
        ),
        migrations.AlterUniqueTogether(
            name='prestamoarma',
            unique_together={('arma', 'competencia', 'deportista_receptor')},
        ),
    ]
