# Generated by Django 5.2.7 on 2025-11-26 21:07

import adtdcbba_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportistas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_deportistas/', validators=[adtdcbba_backend.validators.validate_file_integrity]),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='archivo_responsabilidad',
            field=models.FileField(blank=True, null=True, upload_to='responsabilidades/', validators=[adtdcbba_backend.validators.validate_file_integrity]),
        ),
        migrations.AlterField(
            model_name='documentodeportista',
            name='file',
            field=models.FileField(upload_to='docs_deportistas/', validators=[adtdcbba_backend.validators.validate_file_integrity]),
        ),
    ]
