# Generated by Django 5.2.7 on 2025-11-26 21:24

import adtdcbba_backend.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_initial'),
        ('deportistas', '0003_deportista_foto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arma',
            options={'verbose_name': 'Arma', 'verbose_name_plural': 'Armas'},
        ),
        migrations.AlterModelOptions(
            name='deportista',
            options={'ordering': ['apellido_paterno', 'apellido_materno', 'first_name'], 'verbose_name': 'Deportista', 'verbose_name_plural': 'Deportistas'},
        ),
        migrations.AlterModelOptions(
            name='documentodeportista',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='prestamoarma',
            options={'verbose_name': 'Préstamo de Arma', 'verbose_name_plural': 'Préstamos de Armas'},
        ),
        migrations.AlterField(
            model_name='arma',
            name='deportista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armas', to='deportistas.deportista', verbose_name='Propietario'),
        ),
        migrations.AlterField(
            model_name='arma',
            name='es_aire_comprimido',
            field=models.BooleanField(default=False, verbose_name='Es Aire Comprimido'),
        ),
        migrations.AlterField(
            model_name='arma',
            name='matricula',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='apellido_paterno',
            field=models.CharField(max_length=100, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='archivo_responsabilidad',
            field=models.FileField(blank=True, null=True, upload_to='responsabilidades/', validators=[adtdcbba_backend.validators.validate_file_integrity], verbose_name='Carta de Responsabilidad'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='ci',
            field=models.CharField(max_length=20, unique=True, verbose_name='Cédula de Identidad'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deportistas', to='clubs.club', verbose_name='Club'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='codigo_unico',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código Único'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='departamento_origen',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dpto. Origen'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='es_invitado',
            field=models.BooleanField(default=False, verbose_name='Es Invitado'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_deportistas/', validators=[adtdcbba_backend.validators.validate_file_integrity], verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('INACTIVO', 'Inactivo')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='documentodeportista',
            name='document_type',
            field=models.CharField(choices=[('CI', 'Cédula'), ('Licencia B', 'Licencia'), ('Responsabilidad', 'Responsabilidad'), ('Otro', 'Otro')], max_length=50, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='documentodeportista',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='documentodeportista',
            name='file',
            field=models.FileField(upload_to='docs_deportistas/', validators=[adtdcbba_backend.validators.validate_file_integrity], verbose_name='Archivo'),
        ),
    ]
