# Generated by Django 5.2.7 on 2025-11-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportistas', '0004_alter_arma_options_alter_deportista_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportista',
            name='tipo_modalidad',
            field=models.CharField(choices=[('AIRE', 'Solo Aire (Balines/Postones)'), ('FUEGO', 'Armas de Fuego'), ('MIXTA', 'Mixta (Aire y Fuego)')], default='AIRE', max_length=10, verbose_name='Categoría de Tiro'),
        ),
        migrations.AddField(
            model_name='deportista',
            name='vencimiento_credencial',
            field=models.DateField(blank=True, help_text='Calculado automáticamente: Licencia B o 3 años.', null=True, verbose_name='Vencimiento Credencial'),
        ),
    ]
