# Generated by Django 5.2.7 on 2025-10-04 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('deportistas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Juez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poligono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('numero_licencia', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_vencimiento_licencia', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type', models.CharField(choices=[('Departamental', 'Departamental'), ('Nacional', 'Nacional')], max_length=50)),
                ('status', models.CharField(choices=[('Próxima', 'Próxima'), ('En Progreso', 'En Progreso'), ('Finalizada', 'Finalizada')], default='Próxima', max_length=50)),
                ('numero_convocatoria', models.CharField(blank=True, max_length=20, null=True)),
                ('archivo_convocatoria', models.FileField(blank=True, null=True, upload_to='convocatorias/')),
                ('hora_competencia', models.TimeField(blank=True, null=True)),
                ('categorias', models.ManyToManyField(related_name='competencias', to='competencias.categoria')),
                ('jueces', models.ManyToManyField(related_name='competencias', to='competencias.juez')),
                ('poligono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competencias.poligono')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión/Pago'), ('APROBADA', 'Aprobada e Inscrita'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10)),
                ('costo_inscripcion', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='clubs.club')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='competencias.competencia')),
                ('deportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='deportistas.deportista')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='competencias.modalidad'),
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronda_o_serie', models.CharField(max_length=50)),
                ('detalles_json', models.JSONField(default=dict)),
                ('puntaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='competencias.inscripcion')),
                ('juez_que_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competencias.juez')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.categoria')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.competencia')),
            ],
            options={
                'unique_together': {('competencia', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='CompetenciaJuez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.competencia')),
                ('juez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.juez')),
            ],
            options={
                'unique_together': {('competencia', 'juez')},
            },
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arma_utilizada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deportistas.arma')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='competencias.inscripcion')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.modalidad')),
            ],
            options={
                'unique_together': {('inscripcion', 'modalidad')},
            },
        ),
    ]
