# Generated by Django 5.2.7 on 2025-11-24 03:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calibre_permitido', models.CharField(blank=True, help_text="Ej: '9mm'. Si se define, filtra las armas.", max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Juez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_cobrado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Poligono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('numero_licencia', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_vencimiento_licencia', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateField()),
                ('es_actual', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronda_o_serie', models.CharField(max_length=50)),
                ('detalles_json', models.JSONField(default=dict)),
                ('puntaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('es_descalificado', models.BooleanField(default=False)),
                ('motivo_descalificacion', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_verificacion', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type', models.CharField(choices=[('Departamental', 'Departamental'), ('Nacional', 'Nacional')], max_length=50)),
                ('status', models.CharField(choices=[('Próxima', 'Próxima'), ('En Progreso', 'En Progreso'), ('Finalizada', 'Finalizada')], default='Próxima', max_length=50)),
                ('costo_inscripcion_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('numero_convocatoria', models.CharField(blank=True, max_length=20, null=True)),
                ('archivo_convocatoria', models.FileField(blank=True, null=True, upload_to='convocatorias/')),
                ('resultados_pdf', models.FileField(blank=True, null=True, upload_to='resultados_competencias/')),
                ('hora_competencia', models.TimeField(blank=True, null=True)),
                ('categorias', models.ManyToManyField(related_name='competencias', through='competencias.CategoriaCompetencia', to='competencias.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='categoriacompetencia',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.competencia'),
        ),
        migrations.CreateModel(
            name='CompetenciaJuez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.competencia')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='competencias.competencia')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión/Pago'), ('APROBADA', 'Aprobada e Inscrita'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10)),
                ('costo_inscripcion', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observaciones_pago', models.TextField(blank=True, null=True)),
                ('grupo', models.IntegerField(default=1, help_text='Número de Grupo/Squad')),
                ('carril', models.IntegerField(default=0, help_text='Número de Puesto/Carril')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='clubs.club')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='competencias.competencia')),
            ],
        ),
    ]
