# Generated by Django 5.2.7 on 2025-11-24 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competencias', '0001_initial'),
        ('deportistas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='deportista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='deportistas.deportista'),
        ),
        migrations.AddField(
            model_name='juez',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juez_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competenciajuez',
            name='juez',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.juez'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='jueces',
            field=models.ManyToManyField(related_name='competencias', to='competencias.juez'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='competencias.modalidad'),
        ),
        migrations.AddField(
            model_name='participacion',
            name='arma_utilizada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deportistas.arma'),
        ),
        migrations.AddField(
            model_name='participacion',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competencias.categoria'),
        ),
        migrations.AddField(
            model_name='participacion',
            name='inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='competencias.inscripcion'),
        ),
        migrations.AddField(
            model_name='participacion',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.modalidad'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='poligono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competencias.poligono'),
        ),
        migrations.AddField(
            model_name='record',
            name='antecesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competencias.record'),
        ),
        migrations.AddField(
            model_name='record',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.categoria'),
        ),
        migrations.AddField(
            model_name='record',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.competencia'),
        ),
        migrations.AddField(
            model_name='record',
            name='deportista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportistas.deportista'),
        ),
        migrations.AddField(
            model_name='record',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.modalidad'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='competencias.inscripcion'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='juez_que_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competencias.juez'),
        ),
        migrations.AlterUniqueTogether(
            name='categoriacompetencia',
            unique_together={('competencia', 'categoria')},
        ),
        migrations.AlterUniqueTogether(
            name='competenciajuez',
            unique_together={('competencia', 'juez')},
        ),
        migrations.AlterUniqueTogether(
            name='participacion',
            unique_together={('inscripcion', 'categoria')},
        ),
    ]
