# Generated by Django 5.2.7 on 2025-11-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='costo_limite_global',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si se define, ningún deportista pagará más de este monto, sin importar en cuántas categorías se inscriba.', max_digits=10, null=True, verbose_name='Costo Máximo Global'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='calibre_permitido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Calibre'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='categoriacompetencia',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Categoría'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='archivo_convocatoria',
            field=models.FileField(blank=True, null=True, upload_to='convocatorias/', verbose_name='PDF Convocatoria'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='costo_inscripcion_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Base'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='end_date',
            field=models.DateField(verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='hora_competencia',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='numero_convocatoria',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nro Convocatoria'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='resultados_pdf',
            field=models.FileField(blank=True, null=True, upload_to='resultados_competencias/', verbose_name='PDF Resultados'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='start_date',
            field=models.DateField(verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='status',
            field=models.CharField(choices=[('Próxima', 'Próxima'), ('En Progreso', 'En Progreso'), ('Finalizada', 'Finalizada')], default='Próxima', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='type',
            field=models.CharField(choices=[('Departamental', 'Departamental'), ('Nacional', 'Nacional')], max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='costo_inscripcion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total a Pagar'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Pagado'),
        ),
        migrations.AlterField(
            model_name='juez',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='juez',
            name='license_number',
            field=models.CharField(max_length=50, verbose_name='Nro Licencia'),
        ),
        migrations.AlterField(
            model_name='modalidad',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='poligono',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='poligono',
            name='fecha_vencimiento_licencia',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento Licencia'),
        ),
        migrations.AlterField(
            model_name='poligono',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='poligono',
            name='numero_licencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Licencia'),
        ),
    ]
