# Generated by Django 5.2.7 on 2025-11-26 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0003_competencia_costo_limite_global_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poligono',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poligono_administrado', to=settings.AUTH_USER_MODEL, verbose_name='Administrador del Polígono'),
        ),
    ]
