# Generated by Django 5.2.7 on 2025-11-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0004_poligono_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidad',
            name='es_fuego',
            field=models.BooleanField(default=True, help_text='Si se marca, exige Licencia B o Categoría Mixta/Fuego (excepto menores).', verbose_name='Es Arma de Fuego'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='costo_limite_global',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Límite máximo que pagará un deportista.', max_digits=10, null=True, verbose_name='Costo Máximo Global'),
        ),
    ]
