# Generated by Django 5.2.7 on 2025-11-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0005_modalidad_es_fuego_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='banco_info',
            field=models.TextField(blank=True, help_text="Ej: Cta. Banco Mercantil Nro... o 'Pago en sitio'", null=True, verbose_name='Info Bancaria / Pago'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='contacto_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Contacto'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='contacto_telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono Contacto'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='hora_apertura',
            field=models.TimeField(default='08:00', verbose_name='Apertura Polígono (Céreo)'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='archivo_convocatoria',
            field=models.FileField(blank=True, null=True, upload_to='convocatorias/', verbose_name='PDF Convocatoria (Subido)'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='hora_competencia',
            field=models.TimeField(default='09:00', verbose_name='Inicio Competencia'),
        ),
    ]
