# Generated by Django 5.2.7 on 2025-11-27 20:37

import adtdcbba_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0006_competencia_banco_info_competencia_contacto_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoridadFirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre y Apellido')),
                ('cargo', models.CharField(help_text='Ej: Presidente, Director de Competencia', max_length=100, verbose_name='Cargo Institucional')),
                ('firma_imagen', models.ImageField(help_text='Subir firma escaneada en fondo transparente para los reportes.', upload_to='firmas/', validators=[adtdcbba_backend.validators.validate_file_integrity], verbose_name='Imagen de Firma (PNG Transparente)')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='competencia',
            name='archivo_convocatoria',
            field=models.FileField(blank=True, null=True, upload_to='convocatorias/', verbose_name='PDF Convocatoria (Manual)'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='firmas_reportes',
            field=models.ManyToManyField(blank=True, help_text='Seleccione quiénes aparecerán al pie de la Convocatoria y Certificados.', related_name='competencias_firmadas', to='competencias.autoridadfirma', verbose_name='Autoridades que Firman'),
        ),
    ]
