# Generated by Django 5.2.7 on 2025-11-27 21:03

import adtdcbba_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0007_autoridadfirma_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoridadfirma',
            options={'verbose_name': 'Autoridad / Firma', 'verbose_name_plural': 'Autoridades y Firmas'},
        ),
        migrations.AlterField(
            model_name='autoridadfirma',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desactivar si la persona deja el cargo.'),
        ),
        migrations.AlterField(
            model_name='autoridadfirma',
            name='cargo',
            field=models.CharField(help_text='Ej: Presidente, Director Técnico', max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='autoridadfirma',
            name='firma_imagen',
            field=models.ImageField(help_text='Sube una imagen PNG con fondo transparente de la firma.', upload_to='firmas/', validators=[adtdcbba_backend.validators.validate_file_integrity], verbose_name='Imagen de Firma'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='banco_info',
            field=models.TextField(blank=True, help_text='Ej: Banco X, Cuenta Y. Dejar vacío si es pago en sitio.', null=True, verbose_name='Info Bancaria / Pago'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='firmas_reportes',
            field=models.ManyToManyField(blank=True, related_name='competencias_firmadas', to='competencias.autoridadfirma', verbose_name='Autoridades que Firman (Convocatoria/Diplomas)'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='hora_apertura',
            field=models.TimeField(default='08:00', verbose_name='Hora Apertura (Céreo)'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='hora_competencia',
            field=models.TimeField(default='09:00', verbose_name='Hora Inicio Competencia'),
        ),
    ]
