# Generated by Django 5.2.7 on 2025-11-27 21:14

import adtdcbba_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0008_alter_autoridadfirma_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoridadfirma',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='autoridadfirma',
            name='cargo',
            field=models.CharField(help_text='Ej: Presidente, Director de Competencia', max_length=100, verbose_name='Cargo Institucional'),
        ),
        migrations.AlterField(
            model_name='autoridadfirma',
            name='firma_imagen',
            field=models.ImageField(help_text='Subir firma escaneada en fondo transparente para los reportes.', upload_to='firmas/', validators=[adtdcbba_backend.validators.validate_file_integrity], verbose_name='Imagen de Firma (PNG Transparente)'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='banco_info',
            field=models.TextField(blank=True, help_text='Ingrese la cuenta bancaria o instrucciones de pago para esta competencia.', null=True, verbose_name='Info Bancaria / Pago'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='firmas_reportes',
            field=models.ManyToManyField(blank=True, help_text='Seleccione quiénes aparecerán al pie de la Convocatoria y Certificados.', related_name='competencias_firmadas', to='competencias.autoridadfirma', verbose_name='Autoridades que Firman'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='hora_apertura',
            field=models.TimeField(default='08:00', verbose_name='Apertura Polígono (Céreo)'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='hora_competencia',
            field=models.TimeField(default='09:00', verbose_name='Inicio Competencia'),
        ),
    ]
