# Generated by Django 5.2.7 on 2025-11-28 04:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_initial'),
        ('competencias', '0009_alter_autoridadfirma_activo_and_more'),
        ('deportistas', '0005_deportista_tipo_modalidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoridadfirma',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categoriacompetencia',
            options={'verbose_name': 'Categoría Habilitada', 'verbose_name_plural': 'Categorías Habilitadas'},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.RenameField(
            model_name='record',
            old_name='fecha_registro',
            new_name='fecha_logro',
        ),
        migrations.AlterUniqueTogether(
            name='categoriacompetencia',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='participacion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='autoridadfirma',
            name='firma_imagen',
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='archivo_convocatoria',
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='costo_limite_global',
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='description',
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='firmas_reportes',
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='hora_apertura',
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='hora_competencia',
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='numero_convocatoria',
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='resultados_pdf',
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('competencia', 'deportista')},
        ),
        migrations.RemoveField(
            model_name='juez',
            name='user',
        ),
        migrations.RemoveField(
            model_name='poligono',
            name='fecha_vencimiento_licencia',
        ),
        migrations.RemoveField(
            model_name='record',
            name='antecesor',
        ),
        migrations.RemoveField(
            model_name='record',
            name='competencia',
        ),
        migrations.RemoveField(
            model_name='record',
            name='es_actual',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='motivo_descalificacion',
        ),
        migrations.AddField(
            model_name='autoridadfirma',
            name='firma',
            field=models.ImageField(default='', help_text='Imagen PNG transparente', upload_to='firmas/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoriacompetencia',
            name='costo_especifico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='comprobante_pago',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='fecha_inscripcion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='competencia_origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='competencias.competencia'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='motivo_dq',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resultado',
            name='participacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competencias.participacion'),
        ),
        migrations.AlterField(
            model_name='autoridadfirma',
            name='cargo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='autoridadfirma',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='calibre_permitido',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='banco_info',
            field=models.TextField(blank=True, default='', help_text='Datos bancarios para depósitos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competencia',
            name='contacto_nombre',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competencia',
            name='contacto_telefono',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competencia',
            name='costo_inscripcion_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='jueces',
            field=models.ManyToManyField(blank=True, to='competencias.juez'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='poligono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencias', to='competencias.poligono'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='status',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('En Curso', 'En Curso'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Abierta', max_length=20),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='type',
            field=models.CharField(choices=[('Nacional', 'Nacional'), ('Departamental', 'Departamental'), ('Interno', 'Interno')], default='Departamental', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='juez',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='juez',
            name='license_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='modalidad',
            name='es_fuego',
            field=models.BooleanField(default=True, help_text='Marcar si es arma de fuego. Desmarcar para aire comprimido.'),
        ),
        migrations.AlterField(
            model_name='modalidad',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competencias.categoria'),
        ),
        migrations.AlterField(
            model_name='poligono',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='poligono',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='poligono',
            name='numero_licencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='poligono',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poligono_administrado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='detalles_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='fecha_registro',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='juez_que_registro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='puntaje',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='ronda_o_serie',
            field=models.CharField(default='Final', max_length=50),
        ),
        migrations.DeleteModel(
            name='CompetenciaJuez',
        ),
        migrations.RemoveField(
            model_name='categoriacompetencia',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='participacion',
            name='costo_cobrado',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='carril',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='costo_inscripcion',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='observaciones_pago',
        ),
    ]
